package com.example.numbergame;

import android.annotation.SuppressLint;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.StringTokenizer;

public class MainActivity extends AppCompatActivity {
    private EditText number;
    TextView result,thinking,hint,numberGame,history;
    private static  int time = 5;
    private static int random;
    private static int guess;
    private Animation anim;
    private static boolean correct=false;
    private String myData="";
    @RequiresApi(api = Build.VERSION_CODES.O)
    @SuppressLint("SetTextI18n")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        number = findViewById(R.id.et_number);
        Button submit = findViewById(R.id.btn_submit);
        result = findViewById(R.id.text_result);
        thinking = findViewById(R.id.text_thinking);
        hint = findViewById(R.id.text_hint);
        numberGame = findViewById(R.id.text_number_game);
        history = findViewById(R.id.text_history);
        random = (int) ((Math.random()*10)+1);
        anim = AnimationUtils.loadAnimation(this,R.anim.my_anim);
        thinking.startAnimation(anim);
        loadData();

        //Below Method is just for fun to see random number which will be generated by computer but at the same time random number will change.
        numberGame.setOnClickListener(v-> {
            hint.setText(random+"");
            hint.startAnimation(anim);
            hint.setVisibility(View.INVISIBLE);
            AlertDialog.Builder builder = new AlertDialog.Builder(this);
            builder.setTitle("Number Game").setPositiveButton("Ok", (dialog, which) ->
                    random = (int) ((Math.random()*10)+1)
            ).setCancelable(false);
            builder.show();
        });

        submit.setOnClickListener(v->{
            String num = number.getText().toString().trim();
            if(num.isEmpty()){
                return;
            }
            guess = Integer.parseInt(num);
            if(guess==random){
                result.setText("You guessed the number!\nYou win!");
                correct = true;
            }
            else if(guess>random&&guess>0&&guess<11){
                result.setText("Your guess ("+guess+") is bigger than my number.\nYou have " + (time - 1) + " tries left.");
                number.setText("");
                time--;
                }
            else if(guess<random&&guess>0&&guess<11){
                result.setText("Your guess ("+guess+") is smaller than my number.\nYou have " + (time - 1) + " tries left.");
                number.setText("");
                time--;
            }
            else{
                result.setText("You guess ("+guess+") is not between 1 and 10.\n" +
                        "Please Enter Number between 1 to 10\nYou have "+(time-1)+ " tries left");
                number.setText("");
                time--;
            }

            if(!correct &&time==0){
                time = 5;
                int i = random;
                random = (int) ((Math.random()*10)+1);
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
                LocalDateTime now = LocalDateTime.now();
                AlertDialog.Builder builder = new AlertDialog.Builder(this);
                builder.setTitle("\"You ran out of tries.\nYou lose!\"").setPositiveButton("Try Again",(dialog,which) ->{
                    result.setText("");
                    number.setText("");
                    thinking.startAnimation(anim);
                }).setCancelable(false);
                builder.show();
                saveData(" Lose  | "+i+" | "+dtf.format(now));
                loadData();
            }
            else if(correct){
                time = 5;
                random = (int) ((Math.random()*10)+1);
                correct = false;
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
                LocalDateTime now = LocalDateTime.now();
                AlertDialog.Builder builder = new AlertDialog.Builder(this);
                builder.setTitle("\"Congratulations, You guessed the number! You Won!\"").setPositiveButton("Play Again", (dialog, which) -> {
                    result.setText("");
                    number.setText("");
                    thinking.startAnimation(anim);
                }).setCancelable(false);
                builder.show();
                saveData(" Win  | "+guess+" | "+dtf.format(now));
                loadData();
            }
        });
    }
    private void loadData(){
        myData = "";
        File file = getApplicationContext().getFileStreamPath("MyData.txt");
        String lineFromFile;
        if(file.exists()){
            try{
                BufferedReader reader = new BufferedReader(new InputStreamReader(openFileInput("MyData.txt")));
                while((lineFromFile=reader.readLine())!=null){
                    StringTokenizer tokens = new StringTokenizer(lineFromFile,",");
                    String temp  = tokens.nextToken();
                    myData = myData.concat(temp)+"\n";
                }
                reader.close();
                setTextToTextView();
            }
            catch (RuntimeException | IOException e){
                Toast.makeText(this, "anshul"+e.getMessage(), Toast.LENGTH_SHORT).show();
            }
        }
    }

    private void saveData(String res){
        try{
            FileOutputStream file = openFileOutput("MyData.txt",MODE_PRIVATE);
            OutputStreamWriter outputFile = new OutputStreamWriter(file);
            outputFile.write(myData+res+"\n");
            outputFile.flush();
            outputFile.close();
            Toast.makeText(this, "Successfully Saved!", Toast.LENGTH_SHORT).show();
        }
        catch (IOException e){
            Toast.makeText(this, e.getMessage(), Toast.LENGTH_SHORT).show();
        }
    }
    private void setTextToTextView() {
        StringBuilder text = new StringBuilder();
        text.append(myData);
        history.setText(text);
    }
}